spring:
  
  config:
    name: SpringBootApp

  jpa:    
    show-sql: true
  
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bootdb

logging:
  level:
    org.springframework.web.client: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
     
flyway:
  baselineOnMigrate: false
    